### PR TITLE
Don't throw error on empy argument

### LINKED ISSUE #89: Don't throw error on empy argument
I tried to use an empty value argument like the following:

`$ my-cli command foo=`

And results in the following error:
```erlang
    {'EXIT',
     {function_clause,
      [{clique_error,
	format,
	["my-cli",
	 {error,
	  {invalid_kv_arg,
	   "foo"}}],
	[{file,
	  "/mycli/_build/default/lib/clique/src/clique_error.erl"},
	 {line,
	  29}]},
       {clique,
	print,
	3,
	[{file,
	  "/mycli/_build/default/lib/clique/src/clique.erl"},
	 {line,
	  109}]},
       {clique,
	print,
	2,
	[{file,
	  "/mycli/_build/default/lib/clique/src/clique.erl"},
	 {line,
	  92}]},
       {rpc,
	'-handle_call_call/6-fun-0-',
	5,
	[{file,
	  "rpc.erl"},
	 {line,
	  197}]}]}
}
```

IMHO, instead of raising an error clique should pass an empty string "" as the value or even better catch the error and show a clique message instead of the stack trace.

### PR DESCRIPTION
**Pull request by codeadict**
Fixes #89 

Shows a clique status message instead of throwing an error and stack-trace when an Argument value is empty (For example a user running `$ my-cli command foo=`).

### CODE REVIEW

**Comment by martinsumner** [comment]
Not an expert in clique, but it does seem off that all the other errors in clique_parser are handled and not this.

Should the unit test cover both cases (with and without the '=')?

Other than that I'm in favour

File: src/clique_parser.erl [hunk 1]
```diff
@@ -380,7 +380,7 @@ parse_valid_arg_value_with_equal_sign_test() ->
 %% All arguments must be of type k=v
 parse_invalid_kv_arg_test() ->
     Spec = spec(),
-    Args = ["ayo"],
+    Args = ["ayo="],
```
Comment (martinsumner) [inline src/clique_parser.erl]: Can we test both cases?

**Review by martinsumner — APPROVED** [review]
subject to comment

File: src/clique_parser.erl (hunk 1 above)
Comment (codeadict) [reply src/clique_parser.erl]: Thanks for the quick response, I'll change the test to support both cases as soon as I get time.

Comment (codeadict) [reply src/clique_parser.erl]: Done

**Comment by codeadict** [comment]
The suggested changes were applied.
